# Generated by Django 4.1.7 on 2023-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/users/{{ user.username }}/avatar/'),
        ),
    ]
