# Generated by Django 4.1.7 on 2023-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('B', 'Beginner'), ('F', 'Amateur'), ('E', 'Expert'), ('M', 'Master')], default='B', max_length=1),
        ),
    ]
