# Generated by Django 4.1.7 on 2023-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Expert', 'Expert'), ('Master', 'Master')], default='Beginner', max_length=8),
        ),
    ]
