# Generated by Django 4.1.7 on 2023-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/users/{ user.username }/avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men')], default='M', max_length=10),
        ),
    ]
