# Generated by Django 4.1.7 on 2023-11-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
    ]
