# Generated by Django 4.1.7 on 2023-04-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_created_on'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_slug',
            field=models.SlugField(default='testing', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, height_field=100, help_text='Upload images with your plants', null=True, upload_to='images/users/plants/', width_field=200),
        ),
    ]
