# Generated by Django 4.1.7 on 2023-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Django tag', max_length=128),
        ),
    ]
