# Generated by Django 4.1.7 on 2023-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_tag_post_tag_post_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_slug',
            field=models.SlugField(default='testing'),
        ),
    ]
