# Generated by Django 4.1.7 on 2023-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_created_on'),
        ('blog', '0005_remove_post_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='users.profile'),
        ),
    ]
