# Generated by Django 4.1.7 on 2023-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Write comment'),
            preserve_default=False,
        ),
    ]
