# Generated by Django 4.1.7 on 2023-05-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to='blog.post')),
            ],
            bases=('blog.post',),
        ),
    ]
