# Generated by Django 4.1.7 on 2023-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_age'),
        ('blog', '0013_post_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.ManyToManyField(blank=True, default=None, related_name='shared_post', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
