# Generated by Django 4.1.7 on 2023-05-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_alter_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('short_title', models.CharField(max_length=128)),
                ('latin_title', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='You can write some description about your plant ...', null=True)),
                ('picture', models.ImageField(blank=True, default='images/plant_default.png', null=True, upload_to='images/users/plants/picture/')),
                ('appear_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('real_images', models.ImageField(blank=True, height_field=100, help_text='Upload images with your plants', null=True, upload_to='images/users/plants/images/', width_field=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='users.profile')),
            ],
            options={
                'verbose_name': 'plant',
            },
        ),
    ]
