# Generated by Django 4.1.7 on 2023-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_fav_plants_plant_likes_plant_rel_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='short_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
