# Generated by Django 4.1.7 on 2023-05-18 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0003_alter_plant_category_alter_plant_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='seen_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
