# Generated by Django 4.1.7 on 2023-11-09 10:53

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plant_latin_title_alter_plant_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='real_images',
            field=models.ImageField(blank=True, help_text='Upload images with your plants', null=True, upload_to=plants.models.images_directory_path),
        ),
    ]
